version: '3'

services:
    catalog:
        image: postgres:10.12
        environment:
            - POSTGRES_PASSWORD=testpassword

    irods-catalog-provider:
        build:
            context: ..
        depends_on:
            - catalog

    irods-catalog-consumer:
        build:
            context: ..
        depends_on:
            - irods-catalog-provider
