version: '3'

services:
    catalog:
        image: mysql:8.0
        environment:
            - MYSQL_ROOT_PASSWORD=testpassword
            - MYSQL_USER=irods
            - MYSQL_PASSWORD=testpassword

        # MySQL 8.0 defaults to using UTF-8 (utf8mb4/utf8mb4_0900_ai_ci). iRODS requires that queries
        # be case-sensitive. Therefore, we set the --collation-server option to one that satisfies that
        # requirement.
        #
        # --disable-log-bin is needed so that setup succeeds. Without this option, the following
        # error is produced and setup fails:
        #
        #    ERROR 1418 (HY000): This function has none of DETERMINISTIC, NO SQL,
        #    or READS SQL DATA in its declaration and binary logging is enabled
        #    (you *might* want to use the less safe log_bin_trust_function_creators
        #    variable)
        #
        command: "--transaction-isolation=READ-COMMITTED --collation-server=utf8mb4_0900_as_cs --disable-log-bin"

        # The default docker security profile restricts several things to protect the OS. This results
        # in the MySQL container logging the following on each interaction:
        #
        #    mbind: Operation not permitted
        #
        # This does not have any known impact on testing, but if you feel it does, consider uncommenting
        # the "cap_add" section below. Doing so will resolve the mbind message and may resolve other
        # problems.
        #
        # For more information about this, see the following:
        #
        #    https://github.com/docker-library/mysql/issues/303
        #
        #cap_add:
        #    - SYS_NICE

    irods-catalog-provider:
        build:
            context: ..
            dockerfile: ${dockerfile}
            args:
                - irods_package_version=${irods_package_version}
        depends_on:
            - catalog
        volumes:
            - shared_volume:/irods_testing_environment_mount_dir
    # The core test suite for iRODS uses SIGHUP to reload the server's configuration often.
    # To keep the iRODS Rule Language from failing and producing RE_UNABLE_TO_READ_SESSION_VAR,
    # we bump the maximum amount of shared memory from 64mb to 100mb. This is required because
    # iRODS 5 can have two Agent Factories running simultaneously (due to the SIGHUP).
    shm_size: 100mb

    irods-catalog-consumer:
        build:
            context: ..
            dockerfile: ${dockerfile}
            args:
                - irods_package_version=${irods_package_version}
        depends_on:
            - irods-catalog-provider
        volumes:
            - shared_volume:/irods_testing_environment_mount_dir
    # The core test suite for iRODS uses SIGHUP to reload the server's configuration often.
    # To keep the iRODS Rule Language from failing and producing RE_UNABLE_TO_READ_SESSION_VAR,
    # we bump the maximum amount of shared memory from 64mb to 100mb. This is required because
    # iRODS 5 can have two Agent Factories running simultaneously (due to the SIGHUP).
    shm_size: 100mb

# This volume is mounted on all test servers for detached mode testing which
# requires a common vault.
volumes:
    shared_volume:
