version: '3'

services:
  catalog:
    image: mysql:8.0.29
    environment:
      - MYSQL_ROOT_PASSWORD=testpassword
      - MYSQL_USER=irods
      - MYSQL_PASSWORD=testpassword

    # MySQL 8.0 defaults to using UTF-8 (utf8mb4/utf8mb4_0900_ai_ci). iRODS requires that queries
    # be case-sensitive. Therefore, we set the --collation-server option to one that satisfies that
    # requirement.
    #
    # --disable-log-bin is needed so that setup succeeds. Without this option, the following
    # error is produced and setup fails:
    #
    #    ERROR 1418 (HY000): This function has none of DETERMINISTIC, NO SQL,
    #    or READS SQL DATA in its declaration and binary logging is enabled
    #    (you *might* want to use the less safe log_bin_trust_function_creators
    #    variable)
    #
    command: "--transaction-isolation=READ-COMMITTED --collation-server=utf8mb4_0900_as_cs --disable-log-bin"

    # The default docker security profile restricts several things to protect the OS. This results
    # in the MySQL container logging the following on each interaction:
    #
    #    mbind: Operation not permitted
    #
    # This does not have any known impact on testing, but if you feel it does, consider uncommenting
    # the "cap_add" section below. Doing so will resolve the mbind message and may resolve other
    # problems.
    #
    # For more information about this, see the following:
    #
    #    https://github.com/docker-library/mysql/issues/303
    #
    #cap_add:
    #    - SYS_NICE

  irods-catalog-provider:
    build:
      context: ..
    depends_on:
      - catalog

  irods-catalog-consumer:
    build:
      context: ..
    depends_on:
      - irods-catalog-provider

